services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NUXT_MONGOOSE_URI=mongodb://mongodb:27017/
    labels:
      traefik.enable: "true"
      traefik.http.routers.groupgifts.rule: "Host(`gifts.filippo-orru.com`)"
      traefik.http.routers.groupgifts.entrypoints: "https"
      traefik.http.routers.groupgifts.tls: "true"
      traefik.http.services.groupgifts.loadbalancer.server.port: "3000"
    networks:
      - default
      - traefik
  mongodb:
    image: mongo:8.0.3
    volumes:
      - ./volumes/mongodb:/data/db
    restart: unless-stopped


networks:
  traefik:
    external: true
    name: traefik_proxy